#!/bin/sh

set -eu

if [ $# -ne 1 ]
then
	echo "Usage: $0 ir-file" >&2
	exit 1
fi

if [ -z "$ir" ]
then
	echo "$0: no \$ir" >&2
	exit 1
fi

set +u
if [ -z "$TMPDIR" ]
then TMPDIR=/tmp
fi
set -u

tmp="$TMPDIR"/$$.ir
trap "rm -f '$tmp'" EXIT

irdiff(){
	sed '/#/d' "$1"      >$tmp.in
	"$ir" --emit=ir "$1" >$tmp.out

	diff -u "$tmp.in" "$tmp.out"
}

f="$1"
type=$(head -1 "$f" | sed -n 's;.*test=\([a-z0-9_]*\).*;\1;p')
rest=$(head -1 "$f" | sed -n 's;.*test=[a-z0-9_]* \(.*\);\1;p')

case "$type" in
	irdiff)
		irdiff "$f"
		;;
	grep_*)
		backend=$(echo "$type" | sed 's;grep_;;')
		regex="$rest"

		"$ir" "--emit=$backend" "$f" | grep "$regex" >/dev/null
		;;
	harness)
		"$ir" "$f" > harness/src.s
		(
			cd harness
			make -s

			set +e
			./harness
			ec=$?
			set -e

			[ $ec -eq $rest ]
		)
		;;
	sh)
		export f
		sh <<-!
		$rest
		!
		;;
	*)
		echo "$0: unknown test type '$type'" >&2
		exit 1
		;;
esac
